language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: aladage@gmail.com
  api_key:
    secure: t7sZSy//6j5Rjoqy4RyffBFtIu/rPt4GHN+bWBjGajshsKsenmtspPLR7B5j2p5uTxt0yMQl0h73mySSPZjksKP51QoLbYPlUubBGrVtTjM/GrVpa10RuUGlMPkJ0ExWu8fC7S1kjQ8vw8+innwvGiwrc9REY/PUIcmzjoa9wi4A6MlvJiTxdzTWYrIDs21XnGPrwOJ2KYm0qpLWmAeeEiYxTgu1rz3cQ5OPnXIzsMWutJF0m8bvxrbSRp7nb5Mh5Wk0zLvRyzKlu8fcu7Vdg/1lfw/X1e9CWAZy/1JhIW+0J4J7sdubRkDQU7anEeWQZfINc0Cg+MHXpc3telOk+9Y4fITYyITZRKzA5shUFIrliweqSIW4l6JPW2ore+EXRAE6b17qgJuLvcKjwoeTE1dNOXcPrQexivkmB/tUVn4ZYsccXe+HYCD/1cYLruoZj5rA0iNk9G+FLZtBMTNyKbg3xiCgAOa80bmsiT1ofhGvlxRdKCLwfB6aG1B2qjxr7udCx/6oXLtEMyrR3AfrYKrZG/gn8hSLAaSv3HSIV/gqgebckosZysFavGglxrCU162CQKhtev0B5w4crXqb7oRzKR1yblAlweSRKMFKo0X+HXN2sm5MWGnuDQ/skJ3j7oYgWwVDOxuLT+ue9+YN66UIMyqUj6uQR3SGaK31IxQ=
  on:
    branch: master
    tags: true
    repo: deg-skeletor/skeletor-plugin-tokenreplace
