language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: aladage@gmail.com
  api_key:
    secure: Hn+FtSeIWrvenGRWK8kYFi7efsDOCK9uVauCVNQ19I/n//4dIInpaaHqvZPWnvvq/ql4xu8KTYDeOTvNshMhZTzeVZRCr6eQx9HNrWs7zfRExCspKQ0L58+Xdn9KcFerOYm0zrguA6GOKLZPf/Qa9QzdpFlcBHAgInWAUIXMl8A4DMX5g8lPyUymZ86GgIxEQw59ymirLw3p5cnZTxm2cBelIVWDxeI44GitJ/DRhNQrHema4BqjXSgMxM9F2ayeHZ4DQdpGGvnCV1Ou8vMGOdN5E8+NzOTNZgLELYAHYEUVY+qaHzaFzScIoz7t2gNRl+r3kVMi1cvMMrVPhGhY7G5Vaaa/fA43e95b9JWT1RoO4+3veEfJIpWZkW67X+514JmgwtYC6XcDNZj7nI/orDbCiSwK5omE/baLtYAsX61q67uWqj5b+PvDzzNYi6s+ordJS2QgYfyoMr2jMxebVEVdA/StniBMosh6BU51xX5BIVWY6ndNoOwnjQhuvm87zhKjNDELNlLJ8ikhCdGik+fxMHonwY/sFgLF5sr7D3zjYXiZivKPe/EC/wxcNLd5GfO7mkueX87/MkwlyQwVSvIQB+M3FzkYlPfJnSqsD9Wjod/tENcgtl7D3MYmEjCCRcRc1EoA08kfertKUNGM4KpOFQ2MFm2Kjt2Dg/1OVGU=
  on:
    branch: master
    tags: true
    repo: deg-skeletor/skeletor-plugin-tokenreplace
